### ISSUE TITLE
Found 2 elements with non-unique id #first_name

### ISSUE THREAD

**Issue by RShannon1321** [lonestarvirtual/skyOS#41]
Found 2 elements with non-unique id #first_name on https://lonestarcargo.org/profile/edit

First Name and Last Name Fields both share the #first_name value.

Not essential, just something my inspector found on accident.

**Comment by jvoss** [comment]
Can you provide more detail on this? A cursory look shows that the form is correctly populating the name fields.

**Comment by jvoss** [comment]
Found it. It is in the profile form for the disabled field.

Good catch! This does need updated, however this is a display only (disabled) field so it is relatively low priority as it does not affect functionality.

Thanks for the report!

**Comment by RShannon1321** [comment]
Both inputs on the profile page for first name and last name have the same ID.
```
<div class="form-row">
<div class="col">
<div class="form-group">
<label for="first_name">First Name</label>
<input type="text" name="first_name" id="first_name" value="" disabled="disabled" class="form-control">
<small class="form-text text-muted">
Contact staff to make name changes
</small>
</div>
</div>
<div class="col">
<div class="form-group">
<label for="last_name">Last Name</label>
<input type="text" name="first_name" id="first_name" value="" disabled="disabled" class="form-control">
</div>
</div>
</div>
```

**Comment by RShannon1321** [comment]
Yeah, Like I said. Not important at all, just saw a red light in my inspector. haha

**Comment by jvoss** [comment]
Indeed, found it in the profile _form partial.

Thanks!
