### ISSUE TITLE
Pilot roster page styling updates

### ISSUE THREAD

**Issue by jvoss** [lonestarvirtual/skyOS#64]
https://github.com/lonestarvirtual/skyOS/blob/bd3a66329d6df6e29e2f164a35a31cf81b2c891a/app/views/pilots/index.html.haml#L3

Change this class to just ```.container``` instead of ```.container-fluid``` to match styling of other pages.

Consider adding a "View" button on a far right column to highlight the ability to view more details about a pilot.

**Comment by RShannon1321** [comment]
Would you want the button coded in without the functionality? Is there a view that it should reference when it is clicked?

**Comment by jvoss** [comment]
I was thinking similar to the Pilot logbook view page:

![image](https://user-images.githubusercontent.com/376395/82512312-53a11a80-9ad5-11ea-9300-207375ddc2cc.png)
 
Instead of the link being on the Pilot ID (which is somewhat hidden), make another column on the far right similar to above that has a 'View' button with maybe the magnifying glass icon? 

Open to discussion.

**Comment by RShannon1321** [comment]
Ok, I can get the button programmed in. Ignore the last pull request for this.
